"""add location table

Revision ID: 45562c3fb067
Revises: e6caaf6a7fa9
Create Date: 2023-01-17 14:07:02.673464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45562c3fb067'
down_revision = 'e6caaf6a7fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('city', name=op.f('pk_location'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_city_location'), 'location', ['city'], ['city'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_city_location'), type_='foreignkey')

    op.drop_table('location')
    # ### end Alembic commands ###
